trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'OdontoAzureConnection'   
  webAppName: 'odontospring-api'                        
  packageDirectory: '$(System.DefaultWorkingDirectory)/target'

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '17'
    architecture: 'x64'

- script: mvn clean package -DskipTests
  displayName: 'Build com Maven'

- task: CopyFiles@2
  inputs:
    contents: '**/*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/*.jar'
